// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6NKko4ttUFulM_YapHV78Cni7E4WwpMg',
    appId: '1:99496296014:web:f8a2a39a393a4d8d7b0d1f',
    messagingSenderId: '99496296014',
    projectId: 'attendance-6bfc2',
    authDomain: 'attendance-6bfc2.firebaseapp.com',
    storageBucket: 'attendance-6bfc2.appspot.com',
    measurementId: 'G-GHKHQC20QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xpBEgKBkYBvY0I3KRXhW3XW7rGuP3iY',
    appId: '1:99496296014:android:3ac0b879546664a97b0d1f',
    messagingSenderId: '99496296014',
    projectId: 'attendance-6bfc2',
    storageBucket: 'attendance-6bfc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeYnl_qeJUoaiaN8gz274qLe0ckFJ7h1I',
    appId: '1:99496296014:ios:9424cad765344fa57b0d1f',
    messagingSenderId: '99496296014',
    projectId: 'attendance-6bfc2',
    storageBucket: 'attendance-6bfc2.appspot.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeYnl_qeJUoaiaN8gz274qLe0ckFJ7h1I',
    appId: '1:99496296014:ios:9424cad765344fa57b0d1f',
    messagingSenderId: '99496296014',
    projectId: 'attendance-6bfc2',
    storageBucket: 'attendance-6bfc2.appspot.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6NKko4ttUFulM_YapHV78Cni7E4WwpMg',
    appId: '1:99496296014:web:2646382695dfc2fb7b0d1f',
    messagingSenderId: '99496296014',
    projectId: 'attendance-6bfc2',
    authDomain: 'attendance-6bfc2.firebaseapp.com',
    storageBucket: 'attendance-6bfc2.appspot.com',
    measurementId: 'G-TLX1W1LPEK',
  );
}
